name: classundweapon
version: '1.0.1.3'
main: io.github.nyg404.classWeapon.ClassWeapon
api-version: '1.21'
authors: [ Nagust ]
description: Просто плагин minecraft
depend:
  - TailsLib
softdepend:
  - Placeholder
commands:
  admincreateclass:
  adminaddplayer:
  addxp:
  score:
  checklevel:
  reloadclassweapon: