name: Build and Publish JAR

on:
  push:
    branches:
      - main  # Триггер на пуш в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Операционная система для выполнения

    steps:
      # Шаг 1: Проверка исходного кода
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Установка JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # Шаг 3: Сборка проекта с помощью Maven
      - name: Build with Maven
        run: mvn clean package --file pom.xml

      # Шаг 4: Публикация в GitHub Packages
      - name: Publish to GitHub Packages
        run: mvn deploy -s .github/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Токен для аутентификации
