name: Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up environment variables
        run: |
          echo "MY_GITHUB_NAME=${{ github.actor }}" >> $GITHUB_ENV
          echo "MY_GITHUB_TOKEN=${{ secrets.MY_GITHUB_TOKEN }}" >> $GITHUB_ENV
      

      - name: Build and deploy
        run: mvn deploy

