name: Maven Package

on:
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write


    steps:
      - name: 🛒 мяу
        uses: actions/checkout@v4

      - name: 🔧 ЯВА 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          settings-path: ${{ github.workspace }}

      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s .github/maven/settings.xml

      - name: ⚙️ билд
        run: mvn -B package --file pom.xml

      - name: Проверить содержимое target/
        run: ls -lh target/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
            tag_name: latest
            name: "Latest Release"
            draft: false
            prerelease: false
            files: target/*.jar
        env:
            GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      - name: Publish to GitHub Packages Apache Maven
        run: mvn deploy -s .github/maven/settings.xml
        env:
            GITHUB_TOKEN: ${{ github.token }}

      - name: 🛑 Debug if Upload Failed
        if: failure()
        run: echo "❌ Ошибка загрузки! Проверь target/*.jar"
