name: Maven Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@2
        with:
          java-version: '21'
          distribution: 'zulu'  # используй 'zulu' вместо 'adoptopenjdk'

      - name: Build and Deploy with Maven
        run: |
          mvn clean deploy --settings .github/maven/settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
